final List<String> brazilStates = [
  "Ceará",
  "São Paulo",
  "Rio de Janeiro",
  "Bahia",
  "Minas Gerais",
  "Pernambuco",
  "Paraná",
  "Rio Grande do Sul",
  "Santa Catarina",
  "Maranhão",
  "Goiás",
  "Pará",
  "Paraíba",
  "Espírito Santo",
  "Piauí",
  "Mato Grosso",
  "Alagoas",
  "Rio Grande do Norte",
  "Amazonas",
  "Sergipe",
  "Tocantins",
  "Rondônia",
  "Mato Grosso do Sul",
  "Acre",
  "Amapá",
  "Roraima",
  "Distrito Federal",
];
